# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      - "123:123/udp"
    environment:
      TZ: 'America/Sao_Paulo'
      FTLCONF_webserver_api_password: ${WEBPASSWORD}
      FTLCONF_dns_upstreams: ${PIHOLE_DNS_}
      FTLCONF_dhcp_active: 'false'
      FTLCONF_dns_listeningMode: 'all'
      FTL_CMD: 'no-daemon -- --dns-forward-max 300'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE      
    # deploy:
    #   resources:
    #     limits:
    #       #cpus: '0.001'
    #       memory: 256M
    #     reservations:
    #       #cpus: '0.0001'
    #       memory: 32M
    # Volumes store your data between container upgrades
    volumes:
      - './pihole-conf/etc-pihole:/etc/pihole'
      - './pihole-conf/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
