services:
  unifi-db:
    image: docker.io/mongo:3.6
    container_name: unifi-db
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DBNAME=${MONGO_DBNAME}
    volumes:
      - ./unifi-conf/mongo/data/db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=27017
      - MONGO_DBNAME=${MONGO_DBNAME}
      - MEM_LIMIT=512 #optional
      - MEM_STARTUP=128 #optional
      #- MONGO_TLS= #optional
      #- MONGO_AUTHSOURCE= #optional
    # deploy:
    #   resources:
    #     limits:
    #       #cpus: '0.001'
    #       memory: 512M
    #     reservations:
    #       #cpus: '0.0001'
    #       memory: 128M
    volumes:
      - ./unifi-conf/config:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
